package com.nat.bless.screens.home.presentation

import com.nat.bless.screens.home.domain.models.HomeModel
import com.nat.bless.screens.home.domain.models.HomeResponse

data class HomeState(
    val isLoading: Boolean = false,
    val model: HomeResponse? = null,
    val errorMessage: String? = null,
    val userName: String? = null,
    val lat: String? = null,
    val lng: String? = null,
    val date: String? = null,
){
    companion object {
        val dummyList = listOf(
            HomeModel(
                actualWeight = 2.5,
                collectCharges = 10.0,
                collectedBy = "John Doe",
                collectedDate = "2025-04-20",
                consigneeCode = "CNS001",
                consigneeDestinationAddress = "123 Main St, New York",
                consigneeId = 1,
                consigneeMobile = "1234567890",
                consigneeName = "Alice Smith",
                consigneePhone = "0987654321",
                consigneeReference = "REF001",
                createdBy = 2,
                createdByName = "Admin",
                creationDate = "2025-04-19",
                creationTime = "10:00 AM",
                depositDate = "2025-04-21",
                depositedBy = "Warehouse A",
                destinationCityName = "New York",
                destinationCountryName = "USA",
                destinationThreeLetterCode = "NYC",
                destinationZipCode = "10001",
                hubId = 3,
                hubName = "NY Hub",
                isCheckedToConfirm = true,
                isCollected = true,
                isDeliverd = false,
                isDeposit = true,
                isRecievedByCourier = "true",
                lastStatusActionDate = "2025-04-21",
                lastStatusComment = "In transit",
                lastStatusId = 4,
                lastStatusName = "تم الزيارة",
                lastStatusUpdatedByName = "Admin",
                lastStatusUpdatedDate = "2025-04-21",
                lastStatusUpdatedTime = "02:00 PM",
                originCity = "Los Angeles",
                originCountry = "USA",
                originThreeLetterCode = "LAX",
                originZipCode = "90001",
                remarks = "Handle with care",
                runnerSheetDetailsId = 4,
                shipperCode = "SHP001",
                shipperContactName = "Bob Johnson",
                shipperId = 5,
                shipperName = "Logistics Inc.",
                shipperOriginAddress = "456 Elm St, Los Angeles",
                shipperPhone = "1122334455",
                shipperReference = "SR001",
                transitTime = "2 days",
                waybillCODValue = 100.0,
                waybillComment = "COD - urgent",
                waybillCondition = "Good",
                waybillId = 5,
                waybillPickupDate = "2025-04-19",
                waybillPieces = 1,
                waybillSerial = 5,
                weight = 2.5,
                courierType = "AT"
            ),
            // Repeat with different values for 9 more items
            HomeModel(
                actualWeight = 3.0,
                collectCharges = 15.0,
                collectedBy = "Jane Doe",
                collectedDate = "2025-04-20",
                consigneeCode = "CNS002",
                consigneeDestinationAddress = "456 Oak St, Chicago",
                consigneeId = 4,
                consigneeMobile = "2233445566",
                consigneeName = "Michael Johnson",
                consigneePhone = "6677889900",
                consigneeReference = "REF002",
                createdBy = 4,
                createdByName = "Operator",
                creationDate = "2025-04-19",
                creationTime = "11:00 AM",
                depositDate = "2025-04-21",
                depositedBy = "Warehouse B",
                destinationCityName = "Chicago",
                destinationCountryName = "USA",
                destinationThreeLetterCode = "CHI",
                destinationZipCode = "60601",
                hubId = 4,
                hubName = "Chicago Hub",
                isCheckedToConfirm = true,
                isCollected = true,
                isDeliverd = false,
                isDeposit = true,
                isRecievedByCourier = "true",
                lastStatusActionDate = "2025-04-21",
                lastStatusComment = "Dispatched",
                lastStatusId = 4,
                lastStatusName = "تم الغاء الزيارة",
                lastStatusUpdatedByName = "Operator",
                lastStatusUpdatedDate = "2025-04-21",
                lastStatusUpdatedTime = "03:00 PM",
                originCity = "Houston",
                originCountry = "USA",
                originThreeLetterCode = "HOU",
                originZipCode = "77001",
                remarks = "Fragile",
                runnerSheetDetailsId = 4,
                shipperCode = "SHP002",
                shipperContactName = "Sarah Clark",
                shipperId = 4,
                shipperName = "SpeedX",
                shipperOriginAddress = "789 Maple St, Houston",
                shipperPhone = "2233445566",
                shipperReference = "SR002",
                transitTime = "1 day",
                waybillCODValue = 150.0,
                waybillComment = "Express delivery",
                waybillCondition = "Excellent",
                waybillId = 4,
                waybillPickupDate = "2025-04-19",
                waybillPieces = 2,
                waybillSerial = 4,
                weight = 3.0,
                courierType = "AT"
            ),

            HomeModel(
                actualWeight = 3.0,
                collectCharges = 15.0,
                collectedBy = "Jane Doe",
                collectedDate = "2025-04-20",
                consigneeCode = "CNS002",
                consigneeDestinationAddress = "456 Oak St, Chicago",
                consigneeId = 4,
                consigneeMobile = "2233445566",
                consigneeName = "Michael Johnson",
                consigneePhone = "6677889900",
                consigneeReference = "REF002",
                createdBy = 4,
                createdByName = "Operator",
                creationDate = "2025-04-19",
                creationTime = "11:00 AM",
                depositDate = "2025-04-21",
                depositedBy = "Warehouse B",
                destinationCityName = "Chicago",
                destinationCountryName = "USA",
                destinationThreeLetterCode = "CHI",
                destinationZipCode = "60601",
                hubId = 4,
                hubName = "Chicago Hub",
                isCheckedToConfirm = true,
                isCollected = true,
                isDeliverd = false,
                isDeposit = true,
                isRecievedByCourier = "true",
                lastStatusActionDate = "2025-04-21",
                lastStatusComment = "Dispatched",
                lastStatusId = 4,
                lastStatusName = "قيد التنفيذ",
                lastStatusUpdatedByName = "Operator",
                lastStatusUpdatedDate = "2025-04-21",
                lastStatusUpdatedTime = "03:00 PM",
                originCity = "Houston",
                originCountry = "USA",
                originThreeLetterCode = "HOU",
                originZipCode = "77001",
                remarks = "Fragile",
                runnerSheetDetailsId = 4,
                shipperCode = "SHP002",
                shipperContactName = "Sarah Clark",
                shipperId = 4,
                shipperName = "SpeedX",
                shipperOriginAddress = "789 Maple St, Houston",
                shipperPhone = "2233445566",
                shipperReference = "SR002",
                transitTime = "1 day",
                waybillCODValue = 150.0,
                waybillComment = "Express delivery",
                waybillCondition = "Excellent",
                waybillId = 4,
                waybillPickupDate = "2025-04-19",
                waybillPieces = 2,
                waybillSerial = 5,
                weight = 3.0,
                courierType = "AT"
            ),
        )

    }
}

